

<?php
class BudgetTableSeeder extends Seeder {

    public function run()
    {
        DB::table('budget')->delete();

        
		Budget::create(array('category' => '1', 
							'item' => 'Áo cưới',
							'range1' => '0.5',
							'range2'=> '0.5',
							'range3'=>'0.5','range4'=>'',
		        			'range5'=>''),
		Budget::create(array('category' => '1', 
							'item' => 'Áo dài',
							'range1' => '0.5',
							'range2'=> '0.4',
							'range3'=>'0.4','range4'=>'',
		        			'range5'=>''),
		Budget::create(array('category' => '1', 
							'item' => 'Phụ kiện/ đồ ngủ',
							'range1' => '0', 
							'range2'=> '0.1',
							'range3'=>'0.1','range4'=>'',
		        			'range5'=>''),
		Budget::create(array('category' => '2', 
							'item' => 'Ban nhạc',
							'range1' => '1',
							'range2'=> '1',
							'range3'=>'1','range4'=>'',
		        			'range5'=>''),
		Budget::create(array('category' => '3', 
							'item' => 'Bánh cưới',
							'range1' => '1',
							'range2'=> '1',
							'range3'=>'1','range4'=>'',
		        			'range5'=>''),
		Budget::create(array('category' => '4', 
							'item' => 'xe cộ',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1','range4'=>'',
		        			'range5'=>''),
		Budget::create(array('category' => '5', 
							'item' => 'Trang điểm',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '7', 
							'item' => 'Đãi khách',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '8', 
							'item' => 'Chụp ảnh',
							'range1' => '1',
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '9', 
							'item' => 'Thiệp mời',
							'range1' => '1',
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '10', 
							'item' => 'Trang phục chú rể',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '13', 
							'item' => 'Hoa cầm tay',
							'range1' => '0.5', 
							'range2'=> '0.5',
							'range3'=>'0.5', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '13', 
							'item' => 'Hoa trang trí',
							'range1' => '0.5',
							'range2'=> '0.5',
							'range3'=>'0.5', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '14', 
							'item' => 'Ca sĩ/ MC',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '15', 
							'item' => 'Quay phim',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' ),
		Budget::create(array('category' => '16', 
							'item' => 'Khác',
							'range1' => '1', 
							'range2'=> '1',
							'range3'=>'1', 'range4'=>'',
		        			'range5'=>'' );

    }
}
